name: Java CI with Spring Boot

on:  # ワークフローが実行されるタイミングを定義
  push:
    branches:
      - master #  masterブランチにPushされたとき
  pull_request:
    branches:
      - master  # masterブランチへのPull Request作成時
jobs:
  # ジョブ1: コンパイルの確認
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java project
        run: |
          javac -d sumapp/target/classes sumapp/src/sumapp/*.java

  # ジョブ2: テスト実行
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: compile Java project
        run: |
          javac -d sumapp/target/classes sumapp/src/sumapp/*.java

      - name: Run manual test
        run: |
          java -cp sumapp/target/classes sumapp.TestSumApp > test_output.txt
          if grep -q "Test failed" test_output.txt; then
            echo "Test failed due to incorrect calculation."
            exit 1
          else
            echo "All tests passed."
          fi
          
  # ジョブ3: ドキュメントの静的解析
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up linter
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Lint Java files
        run: |
          find sumapp/src/sumapp/ -name "*.java" -print0 | xargs shellcheck || echo "Lint warnings found."
