name: Java CI with Spring Boot

on:  # ワークフローが実行されるタイミングを定義
  push:
    branches:
      - master #  masterブランチにPushされたとき
  pull_request:
    branches:
      - master  # masterブランチへのPull Request作成時
jobs:
  build:
    runs-on: ubuntu-latest  # ビルドを実行するOS

    steps:
    # リポジトリをクローン
    - name: Checkout repository
      uses: actions/checkout@v2

    # ディレクトリ構成を確認
    - name: List directory structure
      run: |
       ls -R

    # Javaのセットアップ(JDK17)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # 必要なJDKのバージョン
        distribution: 'temurin'  # 使用するJavaディストリビューション

    # Javaソースコードをコンパイル
    - name: Compile Java project
      run: |
        mkdir -p target
        javac -d target sumapp/src/sumapp/*.java  # sumapp/src/sumapp内のすべてのJavaファイルをコンパイル

    # 手動テストの実行
    - name: Run manual test
      run: |
        java -cp target sumapp.TestSumApp  # TestSumAppクラスを実行

    # 結果の出力
    - name: Output result
      run: echo "Test completed."
