name: Java CI with Spring Boot

on:  # ワークフローが実行されるタイミングを定義
  push:
    branches:
      - master #  masterブランチにPushされたとき
  pull_request:
    branches:
      - master  # masterブランチへのPull Request作成時
jobs:
  build:
    runs-on: ubuntu-latest  # ビルドを実行するOS

    steps:
    # リポジトリをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v4

    # Javaのセットアップ(JDK17)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'  # 必要なJDKのバージョン
        distribution: 'temurin'  # 使用するJavaディストリビューション

    # Javaソースコードをコンパイル
    - name: Compile Java project
      run: |
        javac -d sumapp/target/classes sumapp/src/sumapp/*.java  # sumapp/src/sumapp内のすべてのJavaファイルをコンパイル

    # 手動テストの実行
    - name: Run manual test
      id: test
      run: |
        java -cp sumapp/target/classes sumapp.TestSumApp > test_output.txt # TestSumAppクラスを実行
        if grep -q "Test failed" test_output.txt; then  # テストに失敗したとき
          echo "Test failed due to incorrect calculation."
          exit 1
        else
          echo "All tests passed."
        fi

    # 結果の出力
    - name: Output result
      run: echo "Test completed."
