name: Lint GitHub Actions Workflows

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  actionlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: rhysd/actionlint@v1.0.0
